# Generated by Django 5.2.5 on 2025-08-25 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_vacancy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='video_resume',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ადმინისტრატორი'), ('job_seeker', 'სამუშაოს მაძიებელი'), ('employer', 'დამსაქმებელი')], max_length=20),
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('video_resume', models.FileField(blank=True, null=True, upload_to='video_resumes/')),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('diploma_upload', models.FileField(blank=True, null=True, upload_to='diplomas/')),
                ('languages', models.ManyToManyField(blank=True, to='core.language')),
            ],
        ),
    ]
