# Generated by Django 5.2.5 on 2025-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_google_access_token_user_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
