# Generated by Django 5.2.5 on 2025-09-05 14:04

from django.db import migrations, models

def populate_slugs(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    for category in Category.objects.all():
        if not category.slug:
            category.slug = category.name.lower().replace(" ", "-")
            category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVacancy',
            fields=[],
            options={
                'verbose_name': 'my Vacancy',
                'verbose_name_plural': 'my Vacancy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.vacancy',),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RunPython(populate_slugs),  # <== ეს გემრიელად გადაჭრის ყველაფერს
    ]
