# Generated by Django 5.2.5 on 2025-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_myvacancy_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
