# Generated by Django 5.2.5 on 2025-09-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
