# Generated by Django 5.2.5 on 2025-09-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_application_interview_end_application_interview_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_event_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
