# Generated by Django 5.2.5 on 2025-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_application_interview_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
