# Generated by Django 5.2.5 on 2025-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vacancy_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'permissions': (('can_approve_vacancies', 'Can approve vacancies'),)},
        ),
    ]
