# Generated by Django 5.2.5 on 2025-09-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_vacancy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyJobSeekerProfile',
            fields=[],
            options={
                'verbose_name': 'myprofile',
                'verbose_name_plural': 'myprofile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.jobseekerprofile',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('field', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B1', max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_items', to='core.jobseekerprofile')),
            ],
            options={
                'unique_together': {('profile', 'language')},
            },
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
