# Generated by Django 5.2.5 on 2025-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_migrate_languages_to_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
