# Generated by Django 5.2.5 on 2025-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_jobseekerprofile_education_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
