# Generated by Django 5.2.5 on 2025-09-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_jobseekerprofile_languages_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
