# Generated by Django 5.2.5 on 2025-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jobseekerprofile_cv_alter_application_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
