# Generated by Django 5.2.5 on 2025-09-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_jobseekerprofile_skills_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
