# Generated by Django 5.2.5 on 2025-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_vacancy_latitude_vacancy_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
