# Generated by Django 5.2.5 on 2025-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_vacancy_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
    ]
