# Generated by Django 5.2.5 on 2025-09-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_jobseekerprofile_preferred_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredVacancy',
            fields=[
            ],
            options={
                'verbose_name': 'სასურველი ვაკანსია',
                'verbose_name_plural': 'სასურველი ვაკანსიები',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.vacancy',),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
