# Generated by Django 5.2.5 on 2025-09-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_preferredvacancy_vacancy_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedservice',
            name='remaining_premium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedservice',
            name='remaining_standard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_limit',
            field=models.IntegerField(default=0),
        ),
    ]
