# Generated by Django 5.2.5 on 2025-09-16 15:06

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_invoice_invoice_number_remove_invoice_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[core.validators.validate_cv_file]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='diploma_upload',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/', validators=[core.validators.validate_diploma_file]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='video_resume',
            field=models.FileField(blank=True, null=True, upload_to='video_resumes/', validators=[core.validators.validate_video_file]),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job_seeker', 'vacancy'), name='unique_application_per_jobseeker_vacancy'),
        ),
    ]
