# Generated by Django 5.2.5 on 2025-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_invoice_service_alter_jobseekerprofile_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedservice',
            name='notified_expired',
            field=models.BooleanField(default=False),
        ),
    ]
