# Generated by Django 5.2.5 on 2025-09-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_purchasedservice_notified_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education_data',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='languages_data',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills_data',
        ),
        migrations.CreateModel(
            name='LanguageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_entries', to='core.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='core.jobseekerprofile')),
            ],
        ),
    ]
