# Generated by Django 5.2.5 on 2025-09-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_jobseekerprofile_education_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyJobSeekerProfile',
        ),
    ]
