# Generated by Django 5.2.5 on 2025-09-24 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_employerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employers', to=settings.AUTH_USER_MODEL),
        ),
    ]
