# Generated by Django 5.2.5 on 2025-09-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_test_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='respondent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.application'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('test', 'response_id')},
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['test', 'response_id'], name='core_testre_test_id_7b5966_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['application'], name='core_testre_applica_cab678_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['respondent_email'], name='core_testre_respond_b924f9_idx'),
        ),
    ]
