# Generated by Django 5.2.5 on 2025-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_testresult_respondent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
