# Generated by Django 5.2.5 on 2025-09-27 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_employerprofile_company_id_number_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employers/profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_seekers/profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
