# Generated by Django 5.2.5 on 2025-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_passwordresetpin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='core.category'),
        ),
    ]
