# Generated by Django 5.2.5 on 2025-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_vacancy_category_vacancy_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
